#!/usr/bin/env python3
"""
Regenerates the source files and detection-generating workflows.

Why the shape of this repo is what it is
----------------------------------------
HardenRunnerDetections is keyed (workflow_id HASH, detection RANGE), where
  workflow_id = "<owner>-<repo>-<workflow path with / replaced by ->"
  detection   = "Source-Code-Overwritten-<file basename>"

Neither key carries run_id, job_id or a timestamp. Three consequences drive
everything below:

  1. Re-running a workflow REWRITES the same rows. Runs do not add volume.
  2. Matrix jobs touching the same file collide into one row. A matrix does
     not add volume either, so this repo does not use one.
  3. File is the BASENAME, so basenames must be globally unique or files in
     different directories collide.

Total detections = WORKFLOWS x FILES_PER_WORKFLOW.

The other hard limit is in correlate.go: at most 11 file-overwrite detections
are recorded per step ("if processedCount > 11 { continue }"), so each step
here touches exactly 11 files and the file list is chunked across steps.
"""

import os
import pathlib
import shutil

WORKFLOWS = 5            # distinct workflow files -> distinct workflow_id partitions
FILES_PER_WORKFLOW = 1100  # distinct basenames -> distinct detection sort keys
FILES_PER_STEP = 11      # hard cap in correlate.go; more per step is discarded

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "src"
WF = ROOT / ".github" / "workflows"


def chunk(items, n):
    for i in range(0, len(items), n):
        yield items[i:i + n]


def main():
    if SRC.exists():
        shutil.rmtree(SRC)
    SRC.mkdir(parents=True)

    names = [f"module-{i:05d}.js" for i in range(FILES_PER_WORKFLOW)]
    for name in names:
        (SRC / name).write_text(
            f"// {name}\n"
            "// Checked-in source. The workflows overwrite this file during a run,\n"
            "// which is what Harden-Runner reports as Source-Code-Overwritten.\n"
            f"export const id = '{name}';\n"
            "export function run() { return id; }\n"
        )

    for existing in WF.glob("generate-*.yml"):
        existing.unlink()
    WF.mkdir(parents=True, exist_ok=True)

    steps_per_wf = (FILES_PER_WORKFLOW + FILES_PER_STEP - 1) // FILES_PER_STEP

    for w in range(1, WORKFLOWS + 1):
        lines = [
            f"# Generated by generate.py - do not edit by hand.",
            f"# Produces {FILES_PER_WORKFLOW} Source-Code-Overwritten detections under",
            f"# workflow_id '<owner>-<repo>-.github-workflows-generate-{w:02d}.yml'.",
            f"name: generate-{w:02d}",
            "",
            "on:",
            "  workflow_dispatch:",
            "",
            "permissions:",
            "  contents: read",
            "",
            "jobs:",
            "  overwrite:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - name: Harden Runner",
            # rc-20-int is the int-targeted branch of the action: its
            # src/configs.ts sets STEPSECURITY_ENV="int", so telemetry goes to
            # int.api.stepsecurity.io rather than production. @v2 would send
            # these detections to prod.
            "        uses: step-security/harden-runner@rc-20-int",
            "        with:",
            "          egress-policy: audit",
            "",
            "      - name: Checkout",
            "        uses: actions/checkout@v4",
            "",
        ]
        for idx, batch in enumerate(chunk(names, FILES_PER_STEP), start=1):
            # One step per 11 files: the 12th and beyond in a step are dropped
            # by correlate.go, so packing more in would silently waste them.
            cmds = "\n".join(
                f"          printf '// overwritten\\n' >> src/{n}" for n in batch
            )
            lines += [
                f"      - name: overwrite batch {idx:03d}",
                "        run: |",
                cmds,
                "",
            ]
        (WF / f"generate-{w:02d}.yml").write_text("\n".join(lines) + "\n")

    total = WORKFLOWS * FILES_PER_WORKFLOW
    print(f"{FILES_PER_WORKFLOW} source files in src/")
    print(f"{WORKFLOWS} workflows x {steps_per_wf} overwrite steps each")
    print(f"expected detections after running all workflows once: {total}")


if __name__ == "__main__":
    main()
